#!/bin/bash
# =============================================================================
# Sentinel Backend Deployment Script
# Runs on EC2 (Ubuntu 24.04) — safe to re-run; idempotent.
#
# Usage (from developer machine):
#   EC2_IP=<ip> KEY=~/.ssh/sentinel-key.pem bash infra/deploy-backend.sh
#
# Usage (directly on EC2, e.g. from GitHub Actions via SSH):
#   bash /tmp/deploy-backend.sh
# =============================================================================
set -euo pipefail

APP_DIR="/opt/sentinel"
VENV_DIR="/opt/sentinel-venv"
REPO_URL="https://github.com/daarshnicsanjeev/sentinel-enterprise.git"

# Detect public IP dynamically (used only for the success message)
PUBLIC_IP=$(curl -sf http://checkip.amazonaws.com 2>/dev/null || echo "localhost")

echo "=== Sentinel Backend Deployment ==="
echo "    App dir : $APP_DIR"
echo "    Public IP: $PUBLIC_IP"
echo ""

# ── [1/8] System packages ─────────────────────────────────────────────────────
echo "[1/8] Checking system packages..."
sudo apt-get update -qq
sudo apt-get install -y python3-pip python3-venv git curl tesseract-ocr libmagic1 2>/dev/null || true

# ── [2/8] Clone or update repo ───────────────────────────────────────────────
echo "[2/8] Deploying application code..."
if [ -d "$APP_DIR/.git" ]; then
    echo "  Updating existing repo..."
    cd "$APP_DIR"
    sudo git fetch --quiet origin main
    sudo git reset --hard origin/main
else
    echo "  Cloning repo..."
    sudo git clone --depth 1 "$REPO_URL" "$APP_DIR" || {
        echo "  Could not clone repo — ensure it is public or SSH credentials are configured."
        exit 1
    }
fi

cd "$APP_DIR/backend"

# ── [3/8] Python virtual environment ─────────────────────────────────────────
echo "[3/8] Setting up Python venv..."
sudo python3 -m venv "$VENV_DIR"
sudo "$VENV_DIR/bin/pip" install --upgrade pip --quiet

# ── [4/8] Install Python dependencies ────────────────────────────────────────
echo "[4/8] Installing Python dependencies..."
sudo "$VENV_DIR/bin/pip" install -r requirements.txt --quiet

# ── [5/8] Environment file (create on first run, never overwrite) ─────────────
echo "[5/8] Configuring environment..."
if [ ! -f "$APP_DIR/backend/.env" ]; then
    echo "  Creating .env from defaults..."
    sudo tee "$APP_DIR/backend/.env" > /dev/null <<ENVEOF
# Generated by deploy-backend.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file directly on the EC2 instance to change settings.
LLM_PROVIDER=ollama
OLLAMA_MODEL=gemma3:4b
OLLAMA_BASE_URL=http://localhost:11434
RATE_LIMIT=20
EVAL_THRESHOLD=0.7
REVIEW_MIN_EVIDENCE=1
SENTINEL_API_KEY=
ENVEOF
    echo "  .env created."
else
    echo "  .env already exists — skipping (edit manually to change settings)."
    # Ensure REVIEW_MIN_EVIDENCE is present in existing .env
    if ! grep -q "REVIEW_MIN_EVIDENCE" "$APP_DIR/backend/.env"; then
        echo "" | sudo tee -a "$APP_DIR/backend/.env" > /dev/null
        echo "REVIEW_MIN_EVIDENCE=1" | sudo tee -a "$APP_DIR/backend/.env" > /dev/null
        echo "  Added REVIEW_MIN_EVIDENCE=1 to existing .env."
    fi
fi

# ── [6/8] Systemd service ─────────────────────────────────────────────────────
echo "[6/8] Installing systemd service..."
sudo tee /etc/systemd/system/sentinel.service > /dev/null <<'SVCEOF'
[Unit]
Description=Sentinel FastAPI Backend
After=network.target

[Service]
User=ubuntu
WorkingDirectory=/opt/sentinel/backend
EnvironmentFile=/opt/sentinel/backend/.env
ExecStart=/opt/sentinel-venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVCEOF

# ── [7/8] Start / restart service ────────────────────────────────────────────
echo "[7/8] Starting sentinel service..."
sudo systemctl daemon-reload
sudo systemctl enable sentinel --quiet
sudo systemctl restart sentinel

# ── [8/8] Health check ────────────────────────────────────────────────────────
echo "[8/8] Waiting for service to start..."
for i in 1 2 3 4 5; do
    sleep 3
    if curl -sf http://localhost:8000/api/health > /dev/null 2>&1; then
        echo ""
        echo "✓ Sentinel backend is UP"
        echo "  API health : http://${PUBLIC_IP}:8000/api/health"
        echo "  Docs       : http://${PUBLIC_IP}:8000/docs"
        echo ""
        exit 0
    fi
    echo "  Waiting... (attempt $i/5)"
done

echo ""
echo "⚠ Service may still be starting (Ollama model load takes time)."
echo "  Check logs: sudo journalctl -u sentinel -f"
sudo systemctl status sentinel --no-pager || true
